"""
main.py — FastAPI application entry point.

CONCEPT: FastAPI application lifecycle
----------------------------------------
A FastAPI app goes through a lifecycle:
  1. Startup  — connect to DB, Redis, load config
  2. Running  — handle requests (this is 99% of the time)
  3. Shutdown — close connections cleanly

We manage this via the `lifespan` context manager (introduced in FastAPI 0.93).
It replaced the older @app.on_event("startup") decorators.

CONCEPT: Middleware
--------------------
Middleware wraps every request before it hits your route handlers.
CORSMiddleware handles Cross-Origin Resource Sharing — browsers block
requests from one domain (localhost:3000) to another (localhost:8000)
unless the server explicitly allows it. We configure allowed origins
in settings.ALLOWED_ORIGINS.

CONCEPT: API versioning (/api/v1)
-----------------------------------
We prefix all routes with /api/v1. When we make breaking changes in the
future (new response shapes, removed fields), we create /api/v2 and keep
v1 alive for existing clients. This is standard REST API practice.

HOW TO RUN:
  uvicorn app.main:app --reload
  - app.main   → the file (backend/app/main.py)
  - app        → the FastAPI() instance inside that file
  - --reload   → auto-restart on file changes (development only)

API DOCS (auto-generated by FastAPI):
  http://localhost:8000/docs      ← Swagger UI (interactive)
  http://localhost:8000/redoc     ← ReDoc (cleaner read)
  http://localhost:8000/openapi.json ← raw OpenAPI schema
"""

from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.core.config import settings
from app.core.database import init_db
from app.core.redis import close_redis
from app.api.v1.router import api_router


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Manage application startup and shutdown.

    Everything before `yield` runs on startup.
    Everything after `yield` runs on shutdown.

    This is an async context manager — the `async with` in FastAPI's
    internals calls __aenter__ (startup) and __aexit__ (shutdown) for us.
    """
    # STARTUP
    await init_db()  # Create DB tables if they don't exist
    yield
    # SHUTDOWN
    await close_redis()  # Close Redis connection pool cleanly


app = FastAPI(
    title="Soiree API",
    description="Life events concierge powered by Swiggy MCP — Food, Instamart, Dineout",
    version="1.0.0",
    lifespan=lifespan,
    # In production, disable docs for security:
    # docs_url=None, redoc_url=None
)

# CORS — allow the Next.js frontend to call this API from the browser.
# In development: localhost:3000
# In production: your actual domain (set in .env → ALLOWED_ORIGINS)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ALLOWED_ORIGINS,
    allow_credentials=True,  # needed for cookies/auth headers
    allow_methods=["*"],
    allow_headers=["*"],
)

# Mount all API routes under /api/v1
# The router itself is defined in api/v1/router.py
app.include_router(api_router, prefix="/api/v1")


@app.get("/health", tags=["system"])
async def health():
    """
    Health check endpoint. Used by:
    - Docker/Railway to verify the container is alive
    - Load balancers to route traffic only to healthy instances
    - Your own sanity when something breaks
    """
    return {"status": "ok", "service": "soiree-api", "version": "1.0.0"}
